//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities : DbContext
    {
        public CinemaEntities()
            : base("name=CinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TipoAnimacao> TipoAnimacao { get; set; }
        public virtual DbSet<TipoAudio> TipoAudio { get; set; }
        public virtual DbSet<ImagemFilme> ImagemFilme { get; set; }
        public virtual DbSet<Filme> Filme { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<SalaAudioAnimacao> SalaAudioAnimacao { get; set; }
        public virtual DbSet<vwSala> vwSala { get; set; }
        public virtual DbSet<Sessao> Sessao { get; set; }
        public virtual DbSet<vwSessao> vwSessao { get; set; }
    }
}
