//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaAudioAnimacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalaAudioAnimacao()
        {
            this.Sessao = new HashSet<Sessao>();
        }
    
        public int SalaAudioAnimacaoID { get; set; }
        public int SalaID { get; set; }
        public int TipoAudioID { get; set; }
        public int TipoAnimacaoID { get; set; }
    
        public virtual Sala Sala { get; set; }
        public virtual TipoAudio TipoAudio { get; set; }
        public virtual TipoAnimacao TipoAnimacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessao> Sessao { get; set; }
    }
}
