//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessao
    {
        public int SessaoID { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan HorarioInicio { get; set; }
        public System.TimeSpan HorarioFim { get; set; }
        public int ValorIngresso { get; set; }
        public int SalaAudioAnimacaoID { get; set; }
        public int FilmeID { get; set; }
    
        public virtual Filme Filme { get; set; }
        public virtual SalaAudioAnimacao SalaAudioAnimacao { get; set; }
    }
}
